### ISSUE TITLE
Info about being Group manager missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#25] opened 2020-11-24 12:24 UTC
From http://modulesunraveled.com/organic-groups-7x-2x/organic-groups-setup (Section "Add content: Group # 1"):

> [After adding a first group] we see the group. Notice it says "You are the group manager", this is where the "request group membership" link will be for users who are not a member of the group.

While the "Request group membership" link appears for other people (as expected), I as the author of the group should see the notice "You are the group manager" instead, but the notice is missing.

**Comment by laryn** [comment] 2020-11-24 16:14
It looks like this issue (and a few others) rely on the `html_tag` render element, which has not yet been ported to Backdrop, but there is an issue for it:
https://github.com/backdrop/backdrop-issues/issues/3892

Update: maybe that's not relevant... Digging deeper.

**Comment by schoenid** [comment] 2022-04-09 06:20
I found a workaround with the help of a view and the _Views Conditional_ module. The configuration is as follows:

CONTEXTUAL FILTERS

    (OG membership from user) OG membership: Group ID --> Content ID from URL

RELATIONSHIPS

    OG membership: OG membership from User account
    (Group node from OG membership) Content: Author

FIELDS

    User account: Uid [hidden]
    (author) User account: Uid [hidden]
    Views: Views Conditional (If uid is Equal to [uid_1], output Creator of the group, else output )

(You can use the phrase "You are the group manager" instead of "Creator of the group".)

FILTER CRITERIA

    User account: Active (Active)
    User account: Current (Yes)
    (OG membership from user) OG membership: State (= Active)

**Comment by indigoxela** [comment] 2022-04-09 12:54
@laryn your finding that the missing `html_tag` causes this is correct. There seems to be some discussion / opposition to add it back to core.

My proposal: switch to type '#markup' like that in og_ui/og_ui.module:

```
        // User is the group manager.
        $element[0] = array(
          '#type' => 'markup',
          '#markup' => '<span class="group manager">' . t('You are the group manager') . '</span>',
        );
```
I see three usages of `html_tag` in OG, so that shouldn't be much effort (and we don't have to wait for core).

**Comment by indigoxela** [comment] 2022-04-09 13:34
A PR is now available for testing and review: #54

**Comment by olafgrabienski** [comment] 2022-04-11 09:22
Tested the PR, works for me!

<img width="370" alt="backdrop-og-group-manager" src="https://user-images.githubusercontent.com/14188307/162708393-1d07e8e8-786b-42f6-b46a-a463d97c7edb.png">

**Comment by schoenid** [comment] 2022-04-11 16:01
I can confirm, it works fine.
Now I have both possibilities, either to use it on the groups display, or as a views link on a sidebar.

Thank you all !

**Comment by laryn** [comment] 2022-04-12 13:19
Thanks again to the gang: @indigoxela, @olafgrabienski and @schoenid! Merged.

**Closed as completed** 2022-04-12 13:18 UTC
